routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');
Route::get('article/{slug}/{id}','Frontend\PostsController@show')->name('article.show');
Route::post('article/{id}/comments','Frontend\CommentsController@store')->name('comments.store');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin','middleware' => ['auth','admin']], function () {
    Route::get('/', 'AdminController@index')->name('admin');
    Route::group(['prefix' => 'users'], function () {
        Route::get('/', 'UsersController@index')->name('admin.users');
        Route::get('create', 'UsersController@create')->name('admin.users.create');
        Route::post('store', 'UsersController@store')->name('admin.users.store');
        Route::get('delete/{user_id}', 'UsersController@delete')->name('admin.users.delete');
        Route::get('edit/{user_id}', 'UsersController@edit')->name('admin.users.edit');
        Route::post('update/{user_id}', 'UsersController@update')->name('admin.users.update');

    });
    Route::group(['prefix' => 'posts'], function () {

        Route::get('/', 'PostsController@index')->name('admin.posts');
        Route::get('create', 'PostsController@create')->name('admin.posts.create');
        Route::post('store', 'PostsController@store')->name('admin.posts.store');
        Route::get('delete/{post_id}', 'PostsController@delete')->name('admin.posts.delete');
        Route::get('edit/{post_id}', 'PostsController@edit')->name('admin.posts.edit');
        Route::post('update/{post_id}', 'PostsController@update')->name('admin.posts.update');

    });
    Route::group(['prefix' => 'categories'], function () {

        Route::get('/', 'CategoriesController@index')->name('admin.categories');
        Route::get('create', 'CategoriesController@create')->name('admin.categories.create');
        Route::post('store', 'CategoriesController@store')->name('admin.categories.store');
        Route::get('delete/{category_id}', 'CategoriesController@delete')->name('admin.categories.delete');
        Route::get('edit/{category_id}', 'CategoriesController@edit')->name('admin.categories.edit');
        Route::post('update/{category_id}', 'CategoriesController@update')->name('admin.categories.update');

    });
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use App\Traits\Commentable;
use App\Traits\Taggable;
use App\User;
use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Self_;

class Post extends Model
{
    use Commentable, Taggable;

    const PUBLISHED = 1;
    const FUTURE = 2;
    const DRAFT = 3;
    const PENDING = 4;

    protected $primaryKey = 'post_id';

//    protected $fillable = ['post_title','post_content','post_slug'];
    protected $guarded = ['post_id'];

    public function user()
    {
        return $this->belongsTo(User::class, 'post_author', '');
    }

    public function setPostSlugAttribute($value)
    {
        $this->attributes['post_slug'] = preg_replace('/\s+/', '-', $value);
    }

    public static function postStatuses(int $status = null)
    {
        $statuses = [
            self::DRAFT     => 'پیشنویس',
            self::FUTURE    => 'زمان بندی',
            self::PENDING   => 'بازبینی',
            self::PUBLISHED => 'منتشر شده'
        ];
        if ( ! is_null($status) && in_array($status, array_keys($statuses))) {
            return $statuses[$status];
        }

        return $statuses;
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_post', 'post_id', 'category_id');
    }

    public function getPostImageAttribute()
    {
        return env('APP_URL') . '/uploads/images/' . $this->attributes['post_image'];
    }

    public function scopePublished($query)
    {
        return $query->where('post_status', self::PUBLISHED);
    }

    public function getPostExcerptAttribute()
    {
        $postWords = explode(' ', $this->attributes['post_content']);

        return implode(' ', array_slice($postWords, 0, 20)) . '...';
        //return str_limit($this->attributes['post_content'],100,'...');
    }

    public function getPersianCreatedAtAttribute()
    {
        return verta($this->attributes['created_at'])->format('Y-n-j H:i');
    }

}

app/Http/Controllers/Frontend/CommentsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class CommentsController extends Controller
{
    public function store(Request $request, $id)
    {
        $post = Post::published()->find($id);
        if (is_null($post)) {
            abort(404);
        }
        $newCommentResult = $post->comments()->create([
            'user_id' => Auth::id(),
            'body'    => $request->input('comment_content'),
            'status'  => Comment::MODERATED,
        ]);
        if($newCommentResult &&  $newCommentResult instanceof Comment)
        {
            return redirect()->back()->with('status','دیدگاه شما با موفقیت ثبت گردید.');
        }
    }
}

app/Http/Controllers/Frontend/PostsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostsController extends Controller
{

    public function show(Request $request, $slug, $id)
    {
        $post = Post::published()->find($id);
        if (is_null($post)) {
            abort(404);
        }
        $comments = Comment::approved()->get();
        return view('frontend.articles.show', compact('post','comments'));
    }
}

resources/views/frontend/articles/show.blade.php
@extends('layouts.frontend')
@section('content')
    <!-- Post Content Column -->
    <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ $post->post_title }}</h1>

        <!-- Author -->
        <p class="lead">
            by
            <a href="#">{{ $post->user->name }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>ارسال شده در :{{ $post->persian_created_at }}</p>

        <hr>
        {{ $post->post_content }}
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
            <h5 class="card-header">ارسال دیدگاه:</h5>
            <div class="card-body">
                @if(session('status'))
                    <div class="alert alert-success">
                        <p>{{ session('status') }}</p>
                    </div>
                @endif
                <form action="{{ route('comments.store',[$post->post_id]) }}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <textarea class="form-control" name="comment_content" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">ارسال دیدگاه</button>
                </form>
            </div>
        </div>
    @foreach($comments as $comment)
        <!-- Single Comment -->
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="{{ $comment->user->avatar }}" alt="">
                <div class="media-body">
                    <h5 class="mt-0">{{ $comment->user->name }}</h5>
                    <p>
                        {{ $comment->body }}
                    </p>
                </div>
            </div>
    @endforeach
    <!-- Comment with nested comments -->
        <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus
                odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
                fringilla. Donec lacinia congue felis in faucibus.

                <div class="media mt-4">
                    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                    <div class="media-body">
                        <h5 class="mt-0">Commenter Name</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras
                        purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi
                        vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <div class="media mt-4">
                    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                    <div class="media-body">
                        <h5 class="mt-0">Commenter Name</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras
                        purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi
                        vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

            </div>
        </div>

    </div>
@endsection